import { AdDisplaySlot, AdContentCategory } from '../types/wedding';
import { BRAND_ACCENT } from './brand';

// Initial 3D Spatial Advertising Slots distributed on the Worldmap
export const INITIAL_AD_SLOTS: AdDisplaySlot[] = [
  {
    id: 'ad_billboard_highway',
    title: 'Panneau Événementiel Allée Principale',
    slotType: 'billboard_3d',
    pos: [-34, 0, 14],
    rotY: Math.PI / 6,
    size: [6.4, 3.2],
    locationZone: 'Allée d’Honneur & Cortège',
    currentCampaign: {
      id: 'camp_wedding_welcome',
      title: 'BIENVENUE AU MARIAGE DE CLARA & ALEXANDRE',
      subtitle: '14 Juin 2025 • Célébration, Gastronomie & Soirée dansante',
      category: 'wedding_program',
      isSponsored: false,
      advertiserName: 'Les Mariés',
      ctaText: 'Voir le Programme →',
      targetPlaceId: 'place_ceremonie',
      themeColor: BRAND_ACCENT,
      badgeLabel: 'PROGRAMME DU JOUR J',
    },
    isClaimed: true,
  },
  {
    id: 'ad_totem_mairie',
    title: 'Totem LED Parvis de la Mairie',
    slotType: 'led_totem',
    pos: [-38, 0, 24],
    rotY: 0,
    size: [2.0, 4.2],
    locationZone: 'Parvis Hôtel de Ville',
    currentCampaign: {
      id: 'camp_mairie_civil',
      title: 'CÉRÉMONIE RÉPUBLICAINE • 13H30',
      subtitle: 'Salle des Mariages • Signature du registre officiel',
      category: 'wedding_program',
      isSponsored: false,
      advertiserName: 'Mairie du 1er Arrondissement',
      ctaText: 'Itinéraire Cortège',
      targetPlaceId: 'place_mairie',
      themeColor: '#ffffff',
      badgeLabel: 'OFFICIEL',
    },
    isClaimed: true,
  },
  {
    id: 'ad_window_orangerie',
    title: 'Vitrine Scénographique Grand Banquet',
    slotType: 'shop_window',
    pos: [26, 0, -8],
    rotY: -Math.PI / 4,
    size: [4.8, 2.8],
    locationZone: 'Orangerie Vitrée',
    currentCampaign: {
      id: 'camp_lenotre_menu',
      title: 'MAISON LENÔTRE • HAUTE GASTRONOMIE',
      subtitle: 'Filet de bœuf aux morilles & Pièce montée haute couture',
      category: 'vendor_showcase',
      isSponsored: true,
      sponsorName: 'Maison Lenôtre SA',
      advertiserName: 'Chef Antoine & Lenôtre',
      ctaText: 'Découvrir le Menu 3 Plats',
      targetPlaceId: 'place_reception',
      themeColor: '#ffd700',
      badgeLabel: 'PARTENAIRE GASTRONOMIE',
    },
    isClaimed: true,
    claimedByVendorId: 'vendor_traiteur_etoile',
  },
  {
    id: 'ad_totem_cocktail',
    title: 'Totem Belvédère & Mixologie',
    slotType: 'led_totem',
    pos: [6, 0, 14],
    rotY: Math.PI / 3,
    size: [2.0, 4.0],
    locationZone: 'Jardins & Fontaine Royale',
    currentCampaign: {
      id: 'camp_cocktail_mixology',
      title: 'BAR À COCKTAILS & JAZZ SWING',
      subtitle: 'Champagne d’honneur & Quatuor Harmonie en direct',
      category: 'wedding_program',
      isSponsored: false,
      advertiserName: 'Wedding Planner',
      ctaText: 'Séance Golden Hour (18h45)',
      targetPlaceId: 'place_cocktail',
      themeColor: BRAND_ACCENT,
      badgeLabel: 'ANIMATION COCKTAIL',
    },
    isClaimed: true,
  },
  {
    id: 'ad_truss_dancefloor',
    title: 'Bannière Scénique DJ SoundWave',
    slotType: 'banner_truss',
    pos: [14, 0, -26],
    rotY: 0,
    size: [5.6, 1.6],
    locationZone: 'Scène DJ & Dancefloor',
    currentCampaign: {
      id: 'camp_dj_playlist',
      title: 'SOUNDWAVE LIVE • PROPOSEZ VOS MORCEAUX',
      subtitle: 'Votez en direct sur la DJ Zone interactive',
      category: 'wedding_program',
      isSponsored: false,
      advertiserName: 'DJ SoundWave Live',
      ctaText: 'Ouvrir les Votes DJ (❤️)',
      targetPlaceId: 'place_dancefloor',
      themeColor: BRAND_ACCENT,
      badgeLabel: 'DJ ZONE EN DIRECT',
    },
    isClaimed: true,
    claimedByVendorId: 'vendor_dj_soundwave',
  },
  {
    id: 'ad_totem_station',
    title: 'Écran Info-Trafic Gare TGV & Navettes',
    slotType: 'led_totem',
    pos: [-36, 0, 6],
    rotY: 0,
    size: [2.0, 3.8],
    locationZone: 'Hub Gare & Parking',
    currentCampaign: {
      id: 'camp_shuttle_tracking',
      title: 'NAVETTES VIP • TRANSFERT DOMAINE',
      subtitle: 'Départs toutes les 15 minutes vers la cérémonie',
      category: 'wedding_program',
      isSponsored: false,
      advertiserName: 'Service Chauffeur',
      ctaText: 'Suivre les Navettes GPS',
      targetPlaceId: 'place_parking',
      themeColor: '#38bdf8',
      badgeLabel: 'LOGISTIQUE INVITES',
    },
    isClaimed: true,
  },
];
